name: Client CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ 'master', 'dev', 'test' ]
  #    branches: [ 'master', 'dev' ]
  pull_request:
    branches: [ 'master', 'dev' ]

env:
  CLIENT_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:client

  # Common
  BRANCH_DEV: ${{ vars.BRANCH_DEV }}
  GITHUB_REF: ${{ github.ref }}

  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  DOCKER_NETWORK: ${{ vars.DOCKER_NETWORK }}
  DOCKER_NETWORK_GATEWAY: ${{ vars.DOCKER_NETWORK_GATEWAY }}
  DOCKER_NETWORK_IP_RANGE: ${{ vars.DOCKER_NETWORK_IP_RANGE }}
  DOCKER_NETWORK_SUBNET: ${{ vars.DOCKER_NETWORK_SUBNET }}

  CLIENT_IP: ${{ vars.CLIENT_IP }}
  DATABASE_IP: ${{ vars.DATABASE_IP }}
  DATABASE_PORT: ${{ vars.DATABASE_PORT }}
  NGINX_PORT: ${{ vars.NGINX_PORT }}
  SERVER_PORT_HTTP: ${{ vars.SERVER_PORT_HTTP }}
  SERVER_PORT_WS: ${{ vars.SERVER_PORT_WS }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ vars.SSH_PORT }}

  CONNECTION_CHECK_INTERVAL_MS: ${{ vars.CONNECTION_CHECK_INTERVAL_MS }}
  SPECS_DATA_AMOUNT: ${{ vars.SPECS_DATA_AMOUNT }}
  SPECS_HOOK_TIMEOUT_MS: ${{ vars.SPECS_HOOK_TIMEOUT_MS }}

jobs:
  check:
    name: Check files
    outputs:
      delta: ${{ steps.check.outputs.delta }}
    runs-on: ubuntu-latest
    env:
      EVENT_NAME: ${{ github.event_name }}
      EVENT_BEFORE: ${{ github.event.before }}
      EVENT_AFTER: ${{ github.event.after }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Check modified client source files
        id: check
        shell: bash
        run: bash scripts/check-files.sh client

  ci:
    name: Client CI
    runs-on: ubuntu-latest
    needs: check
#    if: needs.check.outputs.delta == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Docker network
        run: |
          docker network create \
            --driver bridge \
            --subnet $DOCKER_NETWORK_SUBNET \
            --gateway $DOCKER_NETWORK_GATEWAY \
            --ip-range $DOCKER_NETWORK_IP_RANGE \
            $DOCKER_NETWORK

      - name: Compose client test
        run: docker compose --verbose --file docker/docker-compose.test.yml --profile client up --build --abort-on-container-exit

      - name: Login to DockerHub registry
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Push test client image
        if: github.ref != 'refs/heads/master'
        run: docker push $CLIENT_IMAGE

  cd:
    name: Client CD
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/master'
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build production client image
        run: |
          docker build \
            --file docker/configs/client/Dockerfile.prod \
            --tag "${CLIENT_IMAGE}-prod" \
            --build-arg NGINX_PORT=$NGINX_PORT \
            .

      - name: Login to DockerHub registry
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Push production database image
        run: docker push "${CLIENT_IMAGE}-prod"

      - name: Pull and run client image on remote host
        uses: appleboy/ssh-action@v1.0.0
        env:
          CLIENT_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:client
          CLIENT_CONTAINER: client

          DOCKER_NETWORK: ${{ vars.DOCKER_NETWORK }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

          SERVER_HOST_HTTP: ${{ secrets.SERVER_HOST_HTTP }}
          SERVER_HOST_WS: ${{ secrets.SERVER_HOST_WS }}

          CLIENT_IP: ${{ vars.CLIENT_IP }}
          NGINX_PORT: ${{ vars.NGINX_PORT }}
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_PORT_WS: ${{ vars.SERVER_PORT_WS }}
        with:
          host: $SSH_HOST
          port: $SSH_PORT
          username: $SSH_USERNAME
          password: $SSH_PASSWORD
          envs:
            CLIENT_IMAGE,
            CLIENT_CONTAINER,
            
            DOCKER_NETWORK,
            DOCKERHUB_PASSWORD,
            DOCKERHUB_USERNAME,
            
            SERVER_HOST_HTTP,
            SERVER_HOST_WS,
            
            CLIENT_IP,
            NGINX_PORT,
            SERVER_IP,
            SERVER_PORT_WS,
            
            NODE_ENV,
            CLIENT_IMAGE_PROD,
            OLD_IMAGE
          script: |
            set -e
            export CLIENT_CONTAINER=$CLIENT_CONTAINER
            export CLIENT_IMAGE=$CLIENT_IMAGE
            
            export DOCKER_NETWORK=$DOCKER_NETWORK
            export DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD
            export DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
            
            export SERVER_HOST_HTTP=$SERVER_HOST_HTTP
            export SERVER_HOST_WS=$SERVER_HOST_WS
            
            export CLIENT_IP=$CLIENT_IP
            export NGINX_PORT=$NGINX_PORT
            export SERVER_IP=$SERVER_IP
            export SERVER_PORT_WS=$SERVER_PORT_WS
            
            export NODE_ENV=prod
            export CLIENT_IMAGE_PROD="${CLIENT_IMAGE}-prod"
            export OLD_IMAGE=$(docker images -q $CLIENT_IMAGE_PROD)$(echo "fallback")
            
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker pull $CLIENT_IMAGE_PROD

            docker stop $CLIENT_CONTAINER || true
            docker container rm -f $CLIENT_CONTAINER
            docker image rm -f $OLD_IMAGE
            
            command="docker run -dit \
              --restart unless-stopped \
              --publish $NGINX_PORT:$NGINX_PORT \
              --name $CLIENT_CONTAINER \
              --net $DOCKER_NETWORK \
              --ip $CLIENT_IP \
              --env NGINX_PORT \
              --env NODE_ENV \
              --env SERVER_HOST_HTTP \
              --env SERVER_HOST_WS \
              --env SERVER_IP \
              --env SERVER_PORT_WS \
              $CLIENT_IMAGE_PROD"
            echo $command
            eval $command
            docker ps
