name: Server CI

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - 'packages/sb-server/**'
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - 'packages/sb-server/**'
  workflow_dispatch:

jobs:
  ci:
    name: SB-Server CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing MySql
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8mb3'
          collation server: 'utf8mb3_general_ci'
          mysql version: '8.0'
          mysql database: 'games_test'
          mysql root password: ${{ secrets.DB_ROOT_PASSWORD }}
      - name: Installing dependencies
        run: yarn install
      - name: Building
        working-directory: ./packages/sb-server
        run: yarn build
      - name: Testing
        working-directory: ./packages/sb-server
        run: yarn test